### PR TITLE
added multicolumn

### PR DESCRIPTION
**Pull request by l0r3m1psum**

### CODE REVIEW

**Comment by l0r3m1psum** [comment]
sorry I was trying to update my fork, by the way now the the tables have two columns one for the name and one for the type.

**Comment by rm-hull** [comment]
@l0r3m1psum change looks fine, but are you able to fix the merge conflict pls?

**Comment by l0r3m1psum** [comment]
I'm sorry but I'm not really good with git or GitHub, if you can tell me what I should do I would be happy to do it.

**Comment by rm-hull** [comment]
i fixed the merge conflict ... could you please retest to make sure it works as you expect

**Comment by l0r3m1psum** [comment]
> i fixed the merge conflict ... could you please retest to make sure
> it works as you expect


Yes for me it still works, thank you very much for accepting my
pull request, by the way I think that now the README should be
update with a new picture.

**Comment by rm-hull** [comment]
I updated the picture - I like your change, looks much nicer now :+1:
but i had to revert some of the formatting you did, as it gets included in the resultant dot file template

**Comment by l0r3m1psum** [comment]
> I updated the picture - I like your change, looks much nicer now
> 👍 but i had to revert some of the formatting you did, as it gets
> included in the resultant dot file template

Glad you like it, yes reverting the formatting I also think it was
necessary because there were a lot of unneeded whitespaces in the
tables.

**Pull request merged**
